### PR TITLE
Ignore non active record subclasses

### LINKED ISSUE #44: Ignore Non AR subclasses
I've been trying to get an isolated failing spec for this, but I don't quite fully understand the code and specs of this project yet.

If we have `Foo` and that inherits from top level class `Bar` then I'd rather not see any errors or warnings like:

```
Foo does not inherit from ActiveRecord::Base
Bar is missing a parent class.
```

### PR DESCRIPTION
**Pull request by markburns**
Fixes #44, #47, #48

### CODE REVIEW

**Comment by markburns** [comment]
My first encounter with the hound bot. It seems quite useful, but I wonder if you've thought of using rubocop with --autocorrect?

A lot of these issues were already present, but I'm happy to fix them. 
Shall I add some rubocop config so you can tweak to your preferred style?

**Comment by zeisler** [comment]
I've deleted all the style violation about line length.

**Comment by zeisler** [comment]
Thank you for your pull request. I will have time to review it this weekend.

**Comment by markburns** [comment]
BTW, the main changes were done in https://github.com/zeisler/active_mocker/pull/50/commits/137dae1988825bbf1924acebb684b4ee461b3ec8

It is probably worth reviewing that as the intent of the PR. The other stuff is refactoring work mainly to make method simpler/classes shorter etc triggered by hound/rubocop.

I can re-do a PR with just those commits if you like

File: lib/active_mocker/generate.rb [hunk 1]
```diff
@@ -1,119 +1,104 @@
...
 
-    def assure_dir_path_exists(file)
-      unless File.exists?(File.dirname(file))
-        FileUtils::mkdir_p(File.dirname(file))
-      end
+    def constant_from(model_name)
+      constant = model_name.constantize
+      return unless constant.ancestors.include?(ActiveRecord::Base)
+      constant
+    rescue StandardError, LoadError => e
```
Comment (zeisler) [inline lib/active_mocker/generate.rb]: [String#constantize](https://github.com/zeisler/active_mocker/pull/43) can cause a `NameError`, what's the case for `LoadError`. I know StandardError will be a catch all, but I like the thought of calling out specific know failure scenarios.

File: spec/lib/active_mocker/generate_spec.rb [hunk 2]
```diff
@@ -95,11 +97,31 @@
       end
     end
 
+    describe "#active_record_models" do
+      let(:models_dir) { File.join(File.expand_path("../../", __FILE__), "models") }
```
Comment (zeisler) [inline spec/lib/active_mocker/generate_spec.rb]: Can you do the same thing you did on line 12 with only using `File.expand_path`?

File: spec/lib/active_mocker/generate_spec.rb [hunk 3]
```diff
@@ -95,11 +97,31 @@
...
+        end
+      end
+    end
+
     describe "ActiveMocker::Config.disable_modules_and_constants" do
 
       before do
         ActiveMocker::Config.disable_modules_and_constants = set_to
         ActiveMocker::Config.progress_bar                  = false
+        ActiveMocker::Config.model_dir                     = File.join(File.expand_path("../../", __FILE__), "models")
```
Comment (zeisler) [inline spec/lib/active_mocker/generate_spec.rb]: `File.expand_path`

File: spec/lib/active_mocker/generate_spec.rb [hunk 4]
```diff
@@ -126,6 +148,7 @@
 
       before do
         ActiveMocker::Config.progress_bar      = false
+        ActiveMocker::Config.model_dir         = File.join(File.expand_path("../../", __FILE__), "models")
```
Comment (zeisler) [inline spec/lib/active_mocker/generate_spec.rb]: `File.expand_path`

File: lib/active_mocker/file_writer.rb [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+    attribute :model, Object
+    attribute :file, String
+    attribute :display_errors
+    attribute :config
+    attribute :model_names, Array
+
+    def write!
+      assure_dir_path_exists!
+
+      safe_write { |f| process!(f)}
```
Comment (zeisler) [inline lib/active_mocker/file_writer.rb]: I would like this addressed. :)

File: lib/active_mocker/generate.rb (hunk 1 above)
Comment (markburns) [inline lib/active_mocker/generate.rb]: I agree. I don't want to be a smart-ass, but you'd have to answer that yourself :) 
https://github.com/zeisler/active_mocker/blob/fec07efe1650f36c44f7b795225a4cbd4faeaa80/lib/active_mocker/generate.rb#L39

Some of the renaming I've done here was just for clarifying, and obviously makes the PR a little harder to parse, so apologies about that.

For reference: http://blog.nicksieger.com/articles/2006/09/06/rubys-exception-hierarchy/

So having NameError, LoadError instead makes sense. The previous code was just not as precise as it could have been.

I'll add that change in here, as it absolutely makes sense.

File: spec/lib/active_mocker/generate_spec.rb [hunk 6]
```diff
@@ -126,7 +148,8 @@
 
       before do
         ActiveMocker::Config.progress_bar      = false
-        ActiveMocker::Config.single_model_path = File.join(File.expand_path("../../models", __FILE__), "model.rb")
+        ActiveMocker::Config.model_dir         = File.expand_path("../../models", __FILE__)
```
Comment (markburns) [inline spec/lib/active_mocker/generate_spec.rb]: Seems like this bot is still set to complain at 80 characters

File: lib/active_mocker/generate.rb (hunk 1 above)
Comment (markburns) [inline lib/active_mocker/generate.rb]: The above issue has been addressed, but is not showing up in the Github UI as a comment on an outdated diff.

**Comment by markburns** [comment]
OK the issues have been addressed in https://github.com/zeisler/active_mocker/pull/50/commits/524fa38a2e451dff42c030327ea8ef9dd56e3524

File: spec/lib/active_mocker/generate_spec.rb (hunk 6 above)
Comment (zeisler) [inline spec/lib/active_mocker/generate_spec.rb]: Just merged in your RuboCop config

**Comment by markburns** [comment]
This is rebased against latest master, but the history is getting messy. If you've reviewed it and are interested in merging it in I can squash if you like?
